name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/logsem/iris-tutorial/docker-x86-64

    steps:
      - uses: actions/checkout@v4
      - name: make-ci
        run: make ci -j2
