name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/logsem/iris-tutorial

    steps:
      - uses: actions/checkout@v3
      - name: install-gawk
        run: apt install gawk -y
      - name: make-ci
        run: make ci -j2
