name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/logsem/iris-tutorial/docker-x86-64:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4
      - name: test
        run: echo $HOME
      - name: make-ci
        shell: bash -l {0}
        run: make ci -j2
